✨ REDmod Layouts For Native Installs
E1337Kat/cyberpunk2077_ext_redux pull request #245
Opened 2022-10-03 04:54 UTC by effs

- [x] Support each REDmod layout (Canon, Named, Toplevel)
  - [ ] TBD is the Toplevel something we really want to support
- [x] Explicitly handle all REDmod subtypes (archives, scripts, tweaks, sounds)
- [ ] Validate info.json
  - [ ] Generally valid, has name & version
  - [ ] Name === dir
  - [ ] Check sounds defined if sounds? (opt)

- Added io-ts as dependency, provides support for constructing validating decoders (here for info.json but can and should be used for e.g. the AMM JSON as well)

closes #244

2022-10-03 15:31 UTC, E1337Kat reviewed
Looks good so far

2022-10-04 05:34 UTC, effs commented on test/unit/mods.example.redmod.ts
> +});
Ye, added now!

2022-10-04 05:35 UTC, effs commented on src/installers.layouts.ts
> +          `,
Not sure if this makes sense, but if it works, we could

2022-10-05 20:52 UTC, effs commented on test/unit/mods.example.redmod.ts
> +      ],
Yup, fixed!

2022-10-05 20:52 UTC, effs commented on src/installer.redmod.ts
> +    traverse(ApplicativePar)((relative) =>
You'll love the new ones then XD

2022-10-07 15:43 UTC, E1337Kat requested changes
more good changes. not sure if the path hierarchy stuff needs to be explicit or not... I feel like it should be so that it is in line with the actual.

2022-10-07 15:43 UTC, E1337Kat commented on test/unit/mods.example.redmod.ts
> +        path.join(`scripts/core/ai/`),
```suggestion
        path.join(`scripts/core/`),
        path.join(`scripts/core/ai/`),
```
path hierarchy

2022-10-07 15:43 UTC, E1337Kat commented on src/installer.redmod.ts
> +const customSoundLayoutAndValidation = (
I like this. Always good to validate if we can.

2022-10-07 15:43 UTC, E1337Kat commented on src/installer.redmod.ts
>  };
```suggestion
};

```
Maybe it is the ruby dev in me, but I like to have the empty last line for some reason. No need to enforce it though, just commenting here

2022-10-11 16:33 UTC, E1337Kat approved these changes
I think this is good. The tests all pass and I think I follow the logic well enough.

2022-10-11 16:51 UTC, merged